bring "./kubeconfig.w" as k;
bring expect;
bring fs;

let fixture = fs.readJson("{@dirname}/fixtures/host.json");

test "renderKubeConfig" {
  let base64 = fixture.get("kubeconfig").asStr();
  let result = k.renderKubeConfig(base64, name: "my-cluster-name", hostname: "boom.host.com");
  expect.equal(result, {
    "apiVersion": "v1",
    "clusters": [
      {
        "cluster": {
          "insecure-skip-tls-verify": true,
          "server": "https://boom.host.com:7443"
        },
        "name": "my-cluster-name"
      }
    ],
    "contexts": [
      {
        "name": "my-cluster-name",
        "context": {
          "cluster": "my-cluster-name",
          "user": "my-cluster-name"
        }
      }
    ],
    "current-context": "my-cluster-name",
    "kind": "Config",
    "preferences": {},
    "users": [
      {
        "name": "my-cluster-name",
        "user": {
          "client-certificate-data": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lJYnlHa2xLaHo0bVF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNU1UZ3dOVE15TVRSYUZ3MHlOVEE1TVRnd05UTTNNVGxhTUR3eApIekFkQmdOVkJBb1RGbXQxWW1WaFpHMDZZMngxYzNSbGNpMWhaRzFwYm5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5CmJtVjBaWE10WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFERWczMUoKNHJPQitSaGh6Mkg3TklielRNTFBDOHMyOVhTWmpPcVY3NXBmT3BzMC93bUEyakhRbFdsVExIbEU4bldrRWxXaAppb3YrQU5wTmlwTXNKd3VXV1ZvTXBWUnZaUzN1eTBQWDFPR01yREdOcS9HUzQybStzcElpZHM1MmMxUUFWbThCCk1kWGdmZFo4d2ZVUUhpazd6OVExdVhUMzBtSW54RUlVc2hNVm1MSU42KzNTdjU1RGZkWDJnTWNvVE8vTyttWXoKOUlXZlZNNng3U25LK0FjOHcycGJoTGw0RDEzY0tXME5hR3RtS0NLTEYvaCtrcWorclArZkYrWnRERHZiaGpURQpLdXplY215bjhLNnNEQnB1WlVvWUM0REx4M2lZWi9CMjZKRHFMT01EUWpMT0dGWWlPbmRVdnBYeHJYYWEvWm1sCmI1VFd6OSt3VHltK1lTMGRBZ01CQUFHalZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkpBSDNTOWFvcER0ODQ2TQpaOXBCY0sraklSOWhNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJOLzlGVEVXV3pucFNCWFhDNnYzRmZJNVhpClJSc0RGNUpZUE1Wem5zTlI3czJTeWNUYitkN201M0VFQjJSM1pDTGpOdTU2TEtEUzNlSE9Bc1pOb3FlRU9tNXYKdVUwVnJNZTE4eXpjVjhiZXk2eGU4VFVnWXZGbGM5M1hLTW85SjhqN1NvS0Y4LzJ0ZnZBckVFVWFHb0ZBc2hIUQpleUoyYWNVUzlEWmN5Wm80K3JNTDNwVzllUmd3KzZkclNtQUNsRSs1bmVxUXNBejFqRFVFM0U5R1EySEl1R0paClRNTXFYSk1YN1Y2ZEtQRzUrUkdwaFZDcHorQjVuSWZmZmhPcldnWjVNMnl4SmxGRG4yS2xFQUxMT0syRVEzS24KbnM3blZuTksvdzlGRU9hS2xSNTdVMlZ3dE5rWW5Zd3dTTVZYUFhRWENvZUs1ZkhtcGEyM3pSU3k0d2JkCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K",
          "client-key-data": "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeElOOVNlS3pnZmtZWWM5aCt6U0c4MHpDend2TE52VjBtWXpxbGUrYVh6cWJOUDhKCmdOb3gwSlZwVXl4NVJQSjFwQkpWb1lxTC9nRGFUWXFUTENjTGxsbGFES1ZVYjJVdDdzdEQxOVRoakt3eGphdngKa3VOcHZyS1NJbmJPZG5OVUFGWnZBVEhWNEgzV2ZNSDFFQjRwTzgvVU5ibDA5OUppSjhSQ0ZMSVRGWml5RGV2dAowcitlUTMzVjlvREhLRXp2enZwbU0vU0ZuMVRPc2UwcHl2Z0hQTU5xVzRTNWVBOWQzQ2x0RFdoclppZ2lpeGY0CmZwS28vcXovbnhmbWJRdzcyNFkweENyczNuSnNwL0N1ckF3YWJtVktHQXVBeThkNG1HZndkdWlRNml6akEwSXkKemhoV0lqcDNWTDZWOGExMm12MlpwVytVMXMvZnNFOHB2bUV0SFFJREFRQUJBb0lCQUJsWXNGOUlTMGozWFFxNAptZld4dDdwSDYxU1RPOW5SM1FFMUtNakFCOVJDbGVSSEJPM0d0dWdsYlZsYUFpWS9jNmIrNm1hVW5TdmM1a3RjCkZWRjdrOFlIcmxLMVBHZkYwQi9kdmRsbnp0TzdIZ1VjNldLOXpGVFphWG5pZ3d6S0lVcU4yM0YzQVJRY2h2NisKY2FKcmtYdnllWGVZZlJxOTJ3VXdEaW5uTWdqMTJCcEdyUlVDVmFZVDdxdGVPOUlxTXZwNlcrem1MVk8zQnNkZAozVy9YSkNYa0VMTFppT1NoNXlHZmRDQm0wMk1kVjlLQWNUVnk3MFRHSk1IN2hOL0N0UlZWOFhVK21GTW1zdDJ3ClU3WnowUjVPR1JoVVVuRVQ0THRVUWxSTHdYbUtwOFdBc1EvQnFSNUptdmFqV2JXVC8wdHFOQ2dUVFFtSjdlTWQKRzUvYkNRRUNnWUVBMjh6KzFGb1g2d1VId0FJUXI0V0NjendVWTBNcXN2UllHN2Z0YkhIdmpsL2lxNzNEY0FTYgpDKzlnYWVJWmdjbmdVRG5reEpTTS9TV3c2K3RrMk9sdUdRZmJMbmw3dDB1T1NLeHNTQThZaytwK2NHNk9NUHdQCkFhNVRFS2V2K292MnVtdEhtd2h6cklLTmUwMzNIQ21nSGZPYnU5MFpyNGdIaXduM0RjTUlBMTBDZ1lFQTVPQ3YKMG1iVnRxOGFzV1l4RURRNExNaEg2VGlBR2lUZnUwc0Z2ZlpnZ3VMZUxzdDZmUFg5UnNPY0t2QWFNVXdRUUJNNgppbUdrMjd5M1dBMDJ2SjA0cDhieWtISmJOaUJwcXNVUENLemxQbTdZMks0VWlFQXdsTDByUStwTEdUaVFMOHYyCjRZaHlCNW1ZeHRhbGk3NGdwRXNtS0RjRGhFODFJZFIvc3lxSzlNRUNnWUVBcUlmVDFHcUg4RkhaRVdZRCtURDcKUnZRSUJkd1lQMEtPMUNJQXo2ZkVzSHZneHlJbldocU43MmJKbkNZYXZLTlhkT3dPOXBPWVR2bTVZQXNMTmk0MQpsc2VwVFVja2p2UkYwbjh5UDBZajZEWmlZRDdFazlhUWd3OXc3VkpGNG11eThGa1ZmRS9Nc2JjZ1dDejlqZ0IwCm5zS001RXl4UngrYitRWFpBaHBLYUprQ2dZRUFtYzlOR080MnJPQWI1aCt3MVJ6aXEyV2t2ZHhVYWoxaGhUSXoKbDZkYzBGaTV5MlMrMmY5TnlDSm9ib3FRYjVTWVR4Y2MvaVlFYmc3eWYxL1I2d3NWS2RzTzQzZVdTRmViNjBFbQppMFAxZ3ZGbkZLWlg4Z0NCSlZQRElZN3dEUER3Sk03RENHbHppQnYyaVpseUF1a3djbmgyR2d4dWRwbnNNT0huCk4zWmRqNEVDZ1lCeWgvcXBxNWtTaGQzSndpNGJWMElLUCtiVzkwRDJaUkFSYXJpeU1udW11d0VNcmtqck8vOEgKalpxZ3diSGhYdnU0WTZxREQ5UGlNRjhpZ2tBTjNiUGE5Sk1HUzl5NzZ3VURhek1zTnBEbS9HT2VkQUVSaFJDUQorUGd1WHkwNlBlR0dWdmdlMExoUjR1V2dvTkJGTStWSGlzallUa0NqV1FRL21tMTZNRVVjc2c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="
        }
      }
    ]
  });
}