#!/usr/bin/env node
const { main } = require("./cli.cjs");

main(process.argv.slice(2)).catch(e => {
  if (e.message.includes("{\"error\"")) {
    const msg = JSON.parse(e.message);
    console.error(msg.error);
  } else {
    console.error(e);
  }
  process.exit(1);
});
